name: flector
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_toggle_switch: ^0.2.0
  auto_size_text: ^3.0.0-nullsafety.0
  clipboard: ^0.1.3
  coingecko_dart: ^0.1.0
  crypto_font_icons: ^1.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio_http: ^5.0.4
  enume: ^1.1.0
  equatable: ^2.0.3
  flex_color_scheme: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.1.0
  injectable: ^1.4.1
  json_annotation: ^4.1.0
  path_provider: ^2.0.5
  smartstruct: ^1.2.3+1
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: ^2.1.2
  enume_generator: ^1.0.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  injectable_generator: ^1.4.1
  json_serializable: ^5.0.1
  smartstruct_generator: ^1.2.3+1
  flutter_native_splash: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#303030"
  image: assets/images/splash.png
